Wil 7
toniverger/willow pull request #9
Opened 2021-11-15 18:00 UTC by carolainseija

2021-11-15 21:27 UTC, toniverger requested changes

2021-11-15 21:27 UTC, toniverger commented on src/components/Forms/Contact/Index.js
> +    console.log("verificar y enviar")
Imagino que esto es porque todavía no se manda mensaje, pero lo borarría de momento si es eso.

2021-11-15 21:27 UTC, toniverger commented on src/components/Forms/Contact/Index.js
> +          <input name="name" value={infoMail.name} onClick={(e) => information(e)} required className="input" type="text"></input>
esto es un input, no deberíamos usar onClick, entiendo que lo que hace es un onChange

2021-11-15 21:27 UTC, toniverger commented on src/components/Forms/Contact/Index.js
> +          <input name="lastname" value={infoMail.lastname} className="input" type="text" onClick={(e) => information(e)} ></input>
idem anterior

2021-11-15 21:27 UTC, toniverger commented on src/components/Forms/Contact/Index.js
> +          <input name="mail" value={infoMail.mail} className="input_mail" type="text" onClick={(e) => information(e)} ></input>
idem anterior

2021-11-15 21:27 UTC, toniverger commented on src/components/Forms/Contact/Index.js
> +          <textarea name="mensagge" value={infoMail.mensagge} placeholder="Dejanos tu mensaje." onClick={(e) => information(e)} ></textarea>
idem anterior

2021-11-15 21:27 UTC, toniverger commented on src/components/Forms/Work/Index.js
>          <>
En este archivo faltan los onChange y el submit no???

2021-11-15 21:27 UTC, toniverger commented on src/components/Menu/Index.js
> +                <button className="btn-menu" onKeyDown={handleMenu} onClick={handleMenu}>
este `onKeyDown` no activa el botón al tocar cualquier tecla?

2021-11-15 21:27 UTC, toniverger commented on src/components/Navbar/index.js
> +                <Menu open={open} onClick={handleMenu} />
Entiendo que acá lo que querés hacer es que no sea solamente el área del icono para clickear sino un poco más grande, pero tas segura que no alcanza con dejar solo el del div?

2021-11-16 12:04 UTC, carolainseija commented on src/components/Forms/Contact/Index.js
> +    console.log("verificar y enviar")
si

2021-11-16 13:06 UTC, toniverger approved these changes
Approved

2021-11-16 13:06 UTC, merged